name: Bug report
description: File a bug report to help us improve
labels: 'bug'
body:
  - type: markdown
    attributes:
      value: |
        This form is for reporting technical issues. If you have a question or you're looking for general support, please visit the OpenToonz User Forum ([English](https://groups.google.com/g/opentoonz_en) | [日本語](https://groups.google.com/g/opentoonz)) or consult the [Manual](https://opentoonz.readthedocs.io/en/latest/).
        
        Please search existing issues before posting to avoid creating duplicates.
        
        We strongly urge you to test if your issue still persists on the latest nightly build which contains the latest bug fixes before making your report. You can find the latest build [here](https://github.com/opentoonz/opentoonz_nightlies/releases).
  - type: textarea
    attributes:
      label: Description
      placeholder: Please write a clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: We are much more likely to fix your problem if you can provide clear steps for us to reproduce it.
      value: |
        1. 
        2. 
  - type: textarea
    attributes:
      label: Screenshots & Video
      placeholder: Include any screenshots or video that helps illustrate your problem here.
  - type: textarea
    attributes:
      label: Expected Behavior
      placeholder: A clear and concise description of what you expected to happen.
  - type: markdown
    attributes:
      value: |
        ## Your Hardware Information
        Listing your hardware information will help us narrow down the problem.
  - type: dropdown
    attributes:
      label: Operating System
      multiple: false
      options:
        - Windows
        - macOS
        - Linux
    validations:
      required: true
  - type: dropdown
    attributes:
      label: GPU
      description: Please check that your graphics drivers are up to date before posting.
      multiple: false
      options:
        - NVIDIA
        - AMD
        - Intel
  - type: dropdown
    attributes:
      label: Graphics Tablet
      description: If your problem relates to pen input please check that your graphics tablet drivers are up to date before posting.
      multiple: false
      options:
        - Wacom
        - XP-Pen
        - Huion
        - Xencelabs
        - Ugee
        - GAOMON
        - Monoprice
        - Parblo
        - Other
  - type: markdown
    attributes:
      value: |
        ---
        Thank you for taking the time to fill out this bug report!
